// Copyright (c) 2026 the go-widgets/data authors. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license that can be
// found in the LICENSE file at the root of this repository.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/data.proto

package datapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Kind mirrors data.Kind: the scalar type of a Value.
type Kind int32

const (
	Kind_KIND_STRING Kind = 0
	Kind_KIND_INT    Kind = 1
	Kind_KIND_FLOAT  Kind = 2
	Kind_KIND_BOOL   Kind = 3
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "KIND_STRING",
		1: "KIND_INT",
		2: "KIND_FLOAT",
		3: "KIND_BOOL",
	}
	Kind_value = map[string]int32{
		"KIND_STRING": 0,
		"KIND_INT":    1,
		"KIND_FLOAT":  2,
		"KIND_BOOL":   3,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_data_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_proto_data_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{0}
}

// FilterOp mirrors data.FilterOp.
type FilterOp int32

const (
	FilterOp_OP_EQ       FilterOp = 0
	FilterOp_OP_NE       FilterOp = 1
	FilterOp_OP_LT       FilterOp = 2
	FilterOp_OP_LE       FilterOp = 3
	FilterOp_OP_GT       FilterOp = 4
	FilterOp_OP_GE       FilterOp = 5
	FilterOp_OP_CONTAINS FilterOp = 6
)

// Enum value maps for FilterOp.
var (
	FilterOp_name = map[int32]string{
		0: "OP_EQ",
		1: "OP_NE",
		2: "OP_LT",
		3: "OP_LE",
		4: "OP_GT",
		5: "OP_GE",
		6: "OP_CONTAINS",
	}
	FilterOp_value = map[string]int32{
		"OP_EQ":       0,
		"OP_NE":       1,
		"OP_LT":       2,
		"OP_LE":       3,
		"OP_GT":       4,
		"OP_GE":       5,
		"OP_CONTAINS": 6,
	}
)

func (x FilterOp) Enum() *FilterOp {
	p := new(FilterOp)
	*p = x
	return p
}

func (x FilterOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterOp) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_data_proto_enumTypes[1].Descriptor()
}

func (FilterOp) Type() protoreflect.EnumType {
	return &file_proto_data_proto_enumTypes[1]
}

func (x FilterOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterOp.Descriptor instead.
func (FilterOp) EnumDescriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{1}
}

// AggFunc mirrors data.AggFunc.
type AggFunc int32

const (
	AggFunc_AGG_COUNT AggFunc = 0
	AggFunc_AGG_SUM   AggFunc = 1
	AggFunc_AGG_AVG   AggFunc = 2
	AggFunc_AGG_MIN   AggFunc = 3
	AggFunc_AGG_MAX   AggFunc = 4
)

// Enum value maps for AggFunc.
var (
	AggFunc_name = map[int32]string{
		0: "AGG_COUNT",
		1: "AGG_SUM",
		2: "AGG_AVG",
		3: "AGG_MIN",
		4: "AGG_MAX",
	}
	AggFunc_value = map[string]int32{
		"AGG_COUNT": 0,
		"AGG_SUM":   1,
		"AGG_AVG":   2,
		"AGG_MIN":   3,
		"AGG_MAX":   4,
	}
)

func (x AggFunc) Enum() *AggFunc {
	p := new(AggFunc)
	*p = x
	return p
}

func (x AggFunc) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AggFunc) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_data_proto_enumTypes[2].Descriptor()
}

func (AggFunc) Type() protoreflect.EnumType {
	return &file_proto_data_proto_enumTypes[2]
}

func (x AggFunc) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AggFunc.Descriptor instead.
func (AggFunc) EnumDescriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{2}
}

// MutationKind mirrors data.MutationKind.
type MutationKind int32

const (
	MutationKind_MUT_INSERT MutationKind = 0
	MutationKind_MUT_UPDATE MutationKind = 1
	MutationKind_MUT_DELETE MutationKind = 2
)

// Enum value maps for MutationKind.
var (
	MutationKind_name = map[int32]string{
		0: "MUT_INSERT",
		1: "MUT_UPDATE",
		2: "MUT_DELETE",
	}
	MutationKind_value = map[string]int32{
		"MUT_INSERT": 0,
		"MUT_UPDATE": 1,
		"MUT_DELETE": 2,
	}
)

func (x MutationKind) Enum() *MutationKind {
	p := new(MutationKind)
	*p = x
	return p
}

func (x MutationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MutationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_data_proto_enumTypes[3].Descriptor()
}

func (MutationKind) Type() protoreflect.EnumType {
	return &file_proto_data_proto_enumTypes[3]
}

func (x MutationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MutationKind.Descriptor instead.
func (MutationKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{3}
}

// Value mirrors data.Value: a tagged scalar. Only the field named by kind is
// meaningful.
type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          Kind                   `protobuf:"varint,1,opt,name=kind,proto3,enum=datapb.Kind" json:"kind,omitempty"`
	Str           string                 `protobuf:"bytes,2,opt,name=str,proto3" json:"str,omitempty"`
	Int           int64                  `protobuf:"varint,3,opt,name=int,proto3" json:"int,omitempty"`
	Float         float64                `protobuf:"fixed64,4,opt,name=float,proto3" json:"float,omitempty"`
	Bool          bool                   `protobuf:"varint,5,opt,name=bool,proto3" json:"bool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_proto_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_KIND_STRING
}

func (x *Value) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

func (x *Value) GetInt() int64 {
	if x != nil {
		return x.Int
	}
	return 0
}

func (x *Value) GetFloat() float64 {
	if x != nil {
		return x.Float
	}
	return 0
}

func (x *Value) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

// Record mirrors data.Record: a row of named cells.
type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]*Value      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_proto_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{1}
}

func (x *Record) GetFields() map[string]*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Op            FilterOp               `protobuf:"varint,2,opt,name=op,proto3,enum=datapb.FilterOp" json:"op,omitempty"`
	Value         *Value                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_proto_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{2}
}

func (x *Filter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Filter) GetOp() FilterOp {
	if x != nil {
		return x.Op
	}
	return FilterOp_OP_EQ
}

func (x *Filter) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type Sort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Desc          bool                   `protobuf:"varint,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sort) Reset() {
	*x = Sort{}
	mi := &file_proto_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sort) ProtoMessage() {}

func (x *Sort) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sort.ProtoReflect.Descriptor instead.
func (*Sort) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{3}
}

func (x *Sort) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Sort) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

type Agg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Func          AggFunc                `protobuf:"varint,2,opt,name=func,proto3,enum=datapb.AggFunc" json:"func,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agg) Reset() {
	*x = Agg{}
	mi := &file_proto_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agg) ProtoMessage() {}

func (x *Agg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agg.ProtoReflect.Descriptor instead.
func (*Agg) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{4}
}

func (x *Agg) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Agg) GetFunc() AggFunc {
	if x != nil {
		return x.Func
	}
	return AggFunc_AGG_COUNT
}

// Query mirrors data.Query: filter, sort, group, page, aggregate.
type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*Filter              `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	Sorts         []*Sort                `protobuf:"bytes,2,rep,name=sorts,proto3" json:"sorts,omitempty"`
	GroupBy       string                 `protobuf:"bytes,3,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Aggs          []*Agg                 `protobuf:"bytes,6,rep,name=aggs,proto3" json:"aggs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_proto_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{5}
}

func (x *Query) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *Query) GetSorts() []*Sort {
	if x != nil {
		return x.Sorts
	}
	return nil
}

func (x *Query) GetGroupBy() string {
	if x != nil {
		return x.GroupBy
	}
	return ""
}

func (x *Query) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Query) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Query) GetAggs() []*Agg {
	if x != nil {
		return x.Aggs
	}
	return nil
}

// Group mirrors data.Group.
type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Value                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Rows          []*Record              `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	Aggregates    map[string]*Value      `protobuf:"bytes,3,rep,name=aggregates,proto3" json:"aggregates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_proto_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{6}
}

func (x *Group) GetKey() *Value {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Group) GetRows() []*Record {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *Group) GetAggregates() map[string]*Value {
	if x != nil {
		return x.Aggregates
	}
	return nil
}

// View mirrors data.View. The grouped flag distinguishes a grouped view (whose
// Rows is nil and Groups non-nil) from an ungrouped one, which repeated fields
// alone cannot carry across the wire.
type View struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*Record              `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Groups        []*Group               `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Aggregates    map[string]*Value      `protobuf:"bytes,4,rep,name=aggregates,proto3" json:"aggregates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Grouped       bool                   `protobuf:"varint,5,opt,name=grouped,proto3" json:"grouped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *View) Reset() {
	*x = View{}
	mi := &file_proto_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *View) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*View) ProtoMessage() {}

func (x *View) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use View.ProtoReflect.Descriptor instead.
func (*View) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{7}
}

func (x *View) GetRows() []*Record {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *View) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *View) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *View) GetAggregates() map[string]*Value {
	if x != nil {
		return x.Aggregates
	}
	return nil
}

func (x *View) GetGrouped() bool {
	if x != nil {
		return x.Grouped
	}
	return false
}

type Mutation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          MutationKind           `protobuf:"varint,1,opt,name=kind,proto3,enum=datapb.MutationKind" json:"kind,omitempty"`
	Record        *Record                `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	Key           *Value                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mutation) Reset() {
	*x = Mutation{}
	mi := &file_proto_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutation) ProtoMessage() {}

func (x *Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutation.ProtoReflect.Descriptor instead.
func (*Mutation) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{8}
}

func (x *Mutation) GetKind() MutationKind {
	if x != nil {
		return x.Kind
	}
	return MutationKind_MUT_INSERT
}

func (x *Mutation) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *Mutation) GetKey() *Value {
	if x != nil {
		return x.Key
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{9}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{10}
}

func (x *ListResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type MutateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateResponse) Reset() {
	*x = MutateResponse{}
	mi := &file_proto_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateResponse) ProtoMessage() {}

func (x *MutateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateResponse.ProtoReflect.Descriptor instead.
func (*MutateResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{11}
}

var File_proto_data_proto protoreflect.FileDescriptor

const file_proto_data_proto_rawDesc = "" +
	"\n" +
	"\x10proto/data.proto\x12\x06datapb\"w\n" +
	"\x05Value\x12 \n" +
	"\x04kind\x18\x01 \x01(\x0e2\f.datapb.KindR\x04kind\x12\x10\n" +
	"\x03str\x18\x02 \x01(\tR\x03str\x12\x10\n" +
	"\x03int\x18\x03 \x01(\x03R\x03int\x12\x14\n" +
	"\x05float\x18\x04 \x01(\x01R\x05float\x12\x12\n" +
	"\x04bool\x18\x05 \x01(\bR\x04bool\"\x86\x01\n" +
	"\x06Record\x122\n" +
	"\x06fields\x18\x01 \x03(\v2\x1a.datapb.Record.FieldsEntryR\x06fields\x1aH\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.datapb.ValueR\x05value:\x028\x01\"e\n" +
	"\x06Filter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12 \n" +
	"\x02op\x18\x02 \x01(\x0e2\x10.datapb.FilterOpR\x02op\x12#\n" +
	"\x05value\x18\x03 \x01(\v2\r.datapb.ValueR\x05value\"0\n" +
	"\x04Sort\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\bR\x04desc\"@\n" +
	"\x03Agg\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12#\n" +
	"\x04func\x18\x02 \x01(\x0e2\x0f.datapb.AggFuncR\x04func\"\xbf\x01\n" +
	"\x05Query\x12(\n" +
	"\afilters\x18\x01 \x03(\v2\x0e.datapb.FilterR\afilters\x12\"\n" +
	"\x05sorts\x18\x02 \x03(\v2\f.datapb.SortR\x05sorts\x12\x19\n" +
	"\bgroup_by\x18\x03 \x01(\tR\agroupBy\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x1f\n" +
	"\x04aggs\x18\x06 \x03(\v2\v.datapb.AggR\x04aggs\"\xd9\x01\n" +
	"\x05Group\x12\x1f\n" +
	"\x03key\x18\x01 \x01(\v2\r.datapb.ValueR\x03key\x12\"\n" +
	"\x04rows\x18\x02 \x03(\v2\x0e.datapb.RecordR\x04rows\x12=\n" +
	"\n" +
	"aggregates\x18\x03 \x03(\v2\x1d.datapb.Group.AggregatesEntryR\n" +
	"aggregates\x1aL\n" +
	"\x0fAggregatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.datapb.ValueR\x05value:\x028\x01\"\x8d\x02\n" +
	"\x04View\x12\"\n" +
	"\x04rows\x18\x01 \x03(\v2\x0e.datapb.RecordR\x04rows\x12%\n" +
	"\x06groups\x18\x02 \x03(\v2\r.datapb.GroupR\x06groups\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12<\n" +
	"\n" +
	"aggregates\x18\x04 \x03(\v2\x1c.datapb.View.AggregatesEntryR\n" +
	"aggregates\x12\x18\n" +
	"\agrouped\x18\x05 \x01(\bR\agrouped\x1aL\n" +
	"\x0fAggregatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.datapb.ValueR\x05value:\x028\x01\"}\n" +
	"\bMutation\x12(\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x14.datapb.MutationKindR\x04kind\x12&\n" +
	"\x06record\x18\x02 \x01(\v2\x0e.datapb.RecordR\x06record\x12\x1f\n" +
	"\x03key\x18\x03 \x01(\v2\r.datapb.ValueR\x03key\"\r\n" +
	"\vListRequest\"8\n" +
	"\fListResponse\x12(\n" +
	"\arecords\x18\x01 \x03(\v2\x0e.datapb.RecordR\arecords\"\x10\n" +
	"\x0eMutateResponse*D\n" +
	"\x04Kind\x12\x0f\n" +
	"\vKIND_STRING\x10\x00\x12\f\n" +
	"\bKIND_INT\x10\x01\x12\x0e\n" +
	"\n" +
	"KIND_FLOAT\x10\x02\x12\r\n" +
	"\tKIND_BOOL\x10\x03*]\n" +
	"\bFilterOp\x12\t\n" +
	"\x05OP_EQ\x10\x00\x12\t\n" +
	"\x05OP_NE\x10\x01\x12\t\n" +
	"\x05OP_LT\x10\x02\x12\t\n" +
	"\x05OP_LE\x10\x03\x12\t\n" +
	"\x05OP_GT\x10\x04\x12\t\n" +
	"\x05OP_GE\x10\x05\x12\x0f\n" +
	"\vOP_CONTAINS\x10\x06*L\n" +
	"\aAggFunc\x12\r\n" +
	"\tAGG_COUNT\x10\x00\x12\v\n" +
	"\aAGG_SUM\x10\x01\x12\v\n" +
	"\aAGG_AVG\x10\x02\x12\v\n" +
	"\aAGG_MIN\x10\x03\x12\v\n" +
	"\aAGG_MAX\x10\x04*>\n" +
	"\fMutationKind\x12\x0e\n" +
	"\n" +
	"MUT_INSERT\x10\x00\x12\x0e\n" +
	"\n" +
	"MUT_UPDATE\x10\x01\x12\x0e\n" +
	"\n" +
	"MUT_DELETE\x10\x022\x9a\x01\n" +
	"\vDataService\x121\n" +
	"\x04List\x12\x13.datapb.ListRequest\x1a\x14.datapb.ListResponse\x12$\n" +
	"\x05Query\x12\r.datapb.Query\x1a\f.datapb.View\x122\n" +
	"\x06Mutate\x12\x10.datapb.Mutation\x1a\x16.datapb.MutateResponseB#Z!github.com/go-widgets/data/datapbb\x06proto3"

var (
	file_proto_data_proto_rawDescOnce sync.Once
	file_proto_data_proto_rawDescData []byte
)

func file_proto_data_proto_rawDescGZIP() []byte {
	file_proto_data_proto_rawDescOnce.Do(func() {
		file_proto_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_data_proto_rawDesc), len(file_proto_data_proto_rawDesc)))
	})
	return file_proto_data_proto_rawDescData
}

var file_proto_data_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_data_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_data_proto_goTypes = []any{
	(Kind)(0),              // 0: datapb.Kind
	(FilterOp)(0),          // 1: datapb.FilterOp
	(AggFunc)(0),           // 2: datapb.AggFunc
	(MutationKind)(0),      // 3: datapb.MutationKind
	(*Value)(nil),          // 4: datapb.Value
	(*Record)(nil),         // 5: datapb.Record
	(*Filter)(nil),         // 6: datapb.Filter
	(*Sort)(nil),           // 7: datapb.Sort
	(*Agg)(nil),            // 8: datapb.Agg
	(*Query)(nil),          // 9: datapb.Query
	(*Group)(nil),          // 10: datapb.Group
	(*View)(nil),           // 11: datapb.View
	(*Mutation)(nil),       // 12: datapb.Mutation
	(*ListRequest)(nil),    // 13: datapb.ListRequest
	(*ListResponse)(nil),   // 14: datapb.ListResponse
	(*MutateResponse)(nil), // 15: datapb.MutateResponse
	nil,                    // 16: datapb.Record.FieldsEntry
	nil,                    // 17: datapb.Group.AggregatesEntry
	nil,                    // 18: datapb.View.AggregatesEntry
}
var file_proto_data_proto_depIdxs = []int32{
	0,  // 0: datapb.Value.kind:type_name -> datapb.Kind
	16, // 1: datapb.Record.fields:type_name -> datapb.Record.FieldsEntry
	1,  // 2: datapb.Filter.op:type_name -> datapb.FilterOp
	4,  // 3: datapb.Filter.value:type_name -> datapb.Value
	2,  // 4: datapb.Agg.func:type_name -> datapb.AggFunc
	6,  // 5: datapb.Query.filters:type_name -> datapb.Filter
	7,  // 6: datapb.Query.sorts:type_name -> datapb.Sort
	8,  // 7: datapb.Query.aggs:type_name -> datapb.Agg
	4,  // 8: datapb.Group.key:type_name -> datapb.Value
	5,  // 9: datapb.Group.rows:type_name -> datapb.Record
	17, // 10: datapb.Group.aggregates:type_name -> datapb.Group.AggregatesEntry
	5,  // 11: datapb.View.rows:type_name -> datapb.Record
	10, // 12: datapb.View.groups:type_name -> datapb.Group
	18, // 13: datapb.View.aggregates:type_name -> datapb.View.AggregatesEntry
	3,  // 14: datapb.Mutation.kind:type_name -> datapb.MutationKind
	5,  // 15: datapb.Mutation.record:type_name -> datapb.Record
	4,  // 16: datapb.Mutation.key:type_name -> datapb.Value
	5,  // 17: datapb.ListResponse.records:type_name -> datapb.Record
	4,  // 18: datapb.Record.FieldsEntry.value:type_name -> datapb.Value
	4,  // 19: datapb.Group.AggregatesEntry.value:type_name -> datapb.Value
	4,  // 20: datapb.View.AggregatesEntry.value:type_name -> datapb.Value
	13, // 21: datapb.DataService.List:input_type -> datapb.ListRequest
	9,  // 22: datapb.DataService.Query:input_type -> datapb.Query
	12, // 23: datapb.DataService.Mutate:input_type -> datapb.Mutation
	14, // 24: datapb.DataService.List:output_type -> datapb.ListResponse
	11, // 25: datapb.DataService.Query:output_type -> datapb.View
	15, // 26: datapb.DataService.Mutate:output_type -> datapb.MutateResponse
	24, // [24:27] is the sub-list for method output_type
	21, // [21:24] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_proto_data_proto_init() }
func file_proto_data_proto_init() {
	if File_proto_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_data_proto_rawDesc), len(file_proto_data_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_data_proto_goTypes,
		DependencyIndexes: file_proto_data_proto_depIdxs,
		EnumInfos:         file_proto_data_proto_enumTypes,
		MessageInfos:      file_proto_data_proto_msgTypes,
	}.Build()
	File_proto_data_proto = out.File
	file_proto_data_proto_goTypes = nil
	file_proto_data_proto_depIdxs = nil
}
